=== unicorn2828/epam_task4_web_xml/parsing/target/classes/data/gems.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.com/gems"
	xmlns:tns="http://www.example.com/gems" elementFormDefault="qualified">
	<element name="gems">
		<complexType>
			<sequence>
				<element name="gem" type="tns:Gem" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="Gem">
		<sequence>
			<element name="name" type="string" />
			<element name="preciousness" type="string" />
			<element name="parameters" type="tns:Parameters" />
		</sequence>
		<attribute name="origin" type="tns:Origin" use="required" />
		<attribute name="date"  use="required" />
		<attribute name="value" use="optional" default="0">
			<simpleType>
				<restriction base="integer">
					<pattern value="[0-9]{1,5}" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
	<simpleType name="Origin">
		<restriction base="ID">
			<enumeration value="unknow"></enumeration>
			<enumeration value="Congo"></enumeration>
			<enumeration value="Kenia"></enumeration>
			<enumeration value="Russia"></enumeration>
			<enumeration value="Canada"></enumeration>
			<enumeration value="USA"></enumeration>
			<enumeration value="Belgium"></enumeration>
			<enumeration value="China"></enumeration>
			<enumeration value="Australia"></enumeration>
			<enumeration value="Uganda"></enumeration>
			<enumeration value="Belarus"></enumeration>
			<enumeration value="Ukraine"></enumeration>
			<enumeration value="Poland"></enumeration>
			<enumeration value="France"></enumeration>
			<enumeration value="Germany"></enumeration>
			<enumeration value="Norway"></enumeration>
			<enumeration value="Japan"></enumeration>
			<enumeration value="Monaco"></enumeration>
			<pattern value="[A-Za-z]{3,15}" />
		</restriction>
	</simpleType>
	<complexType name="Parameters">
		<sequence>
			<element name="color" type="tns:Color" default="unknow" />
			<element name="transparence" type="positiveInteger" />
			<element name="facets" type="positiveInteger" />
		</sequence>
	</complexType>
	<simpleType name="Color">
		<restriction base="string">
			<enumeration value="unknow"></enumeration>
			<enumeration value="white"></enumeration>
			<enumeration value="blue"></enumeration>
			<enumeration value="green"></enumeration>
			<enumeration value="yellow"></enumeration>
			<enumeration value="red"></enumeration>
			<enumeration value="black"></enumeration>
			<enumeration value="purple"></enumeration>
			<pattern value="([a-zA-Z])[a-zA-Z0-9]{3,10}" />
		</restriction>
	</simpleType>
</schema>

=== unicorn2828/epam_task4_web_xml/parsing/target/classes/data/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.com/gems"
	xsi:schemaLocation="http://www.example.com/gems gems.xsd">
	<gem origin="Kenia" value="1000" date="2020-01-20T19:20">
		<name>diamand</name>
		<preciousness>precious</preciousness>
		<parameters>
			<color>white</color>
			<transparence>100</transparence>
			<facets>70</facets>
		</parameters>
	</gem>
	<gem origin="Congo" value="500" date="2020-01-20T19:21">
		<name>saphir</name>
		<preciousness>semiprecious</preciousness>
		<parameters>
			<color>green</color>
			<transparence>80</transparence>
			<facets>55</facets>
		</parameters>
	</gem>
	<gem origin="USA" value="450" date="2020-01-20T19:22">
		<name>diamand</name>
		<preciousness>precious</preciousness>
		<parameters>
			<color>black</color>
			<transparence>100</transparence>
			<facets>44</facets>
		</parameters>
	</gem>
	<gem origin="Canada" value="200" date="2020-01-20T19:23">
		<name>ametist</name>
		<preciousness>semiprecious</preciousness>
		<parameters>
			<color>blue</color>
			<transparence>70</transparence>
			<facets>45</facets>
		</parameters>
	</gem>
	<gem origin="Australia" value="120" date="2020-01-20T19:24">
		<name>diamand</name>
		<preciousness>precious</preciousness>
		<parameters>
			<color>black</color>
			<transparence>70</transparence>
			<facets>45</facets>
		</parameters>
	</gem>
	<gem origin="Russia" value="400" date="2020-01-20T19:25">
		<name>diamand</name>
		<preciousness>precious</preciousness>
		<parameters>
			<color>white</color>
			<transparence>70</transparence>
			<facets>45</facets>
		</parameters>
	</gem>
	<gem origin="Uganda" value="1200" date="2020-01-20T19:26">
		<name>saphir</name>
		<preciousness>semiprecious</preciousness>
		<parameters>
			<color>blue</color>
			<transparence>70</transparence>
			<facets>45</facets>
		</parameters>
	</gem>
	<gem origin="Belarus" value="80" date="2020-01-20T19:27">
		<name>diamand</name>
		<preciousness>precious</preciousness>
		<parameters>
			<color>yellow</color>
			<transparence>70</transparence>
			<facets>45</facets>
		</parameters>
	</gem>
	<gem origin="Poland" value="200" date="2020-01-20T19:28">
		<name>ametist</name>
		<preciousness>semiprecious</preciousness>
		<parameters>
			<color>blue</color>
			<transparence>70</transparence>
			<facets>45</facets>
		</parameters>
	</gem>
	<gem origin="unknow" value="200" date="2020-01-20T19:29">
		<name>diamand</name>
		<preciousness>precious</preciousness>
		<parameters>
			<color>white</color>
			<transparence>72</transparence>
			<facets>42</facets>
		</parameters>
	</gem>
	<gem origin="Japan" value="200" date="2020-01-20T19:30">
		<name>saphir</name>
		<preciousness>semiprecious</preciousness>
		<parameters>
			<color>blue</color>
			<transparence>77</transparence>
			<facets>55</facets>
		</parameters>
	</gem>
	<gem origin="Belgium" value="234" date="2020-01-20T19:31">
		<name>diamand</name>
		<preciousness>precious</preciousness>
		<parameters>
			<color>white</color>
			<transparence>70</transparence>
			<facets>45</facets>
		</parameters>
	</gem>
	<gem origin="Germany" value="888" date="2020-01-20T19:32">
		<name>diamand</name>
		<preciousness>precious</preciousness>
		<parameters>
			<color>blue</color>
			<transparence>30</transparence>
			<facets>25</facets>
		</parameters>
	</gem>
	<gem origin="France" value="888" date="2020-01-20T19:33">
		<name>diamand</name>
		<preciousness>precious</preciousness>
		<parameters>
			<color>blue</color>
			<transparence>80</transparence>
			<facets>25</facets>
		</parameters>
	</gem>
	<gem origin="Norway" value="300" date="2020-01-20T19:34">
		<name>saphir</name>
		<preciousness>semiprecious</preciousness>
		<parameters>
			<color>green</color>
			<transparence>70</transparence>
			<facets>75</facets>
		</parameters>
	</gem>
	<gem origin="Monaco" value="720" date="2020-01-20T19:35">
		<name>diamand</name>
		<preciousness>precious</preciousness>
		<parameters>
			<color>blue</color>
			<transparence>60</transparence>
			<facets>15</facets>
		</parameters>
	</gem>
</gems>

=== unicorn2828/epam_task4_web_xml/parsing/src/main/resources/data/gemsNotValid.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.com/gems"
	xsi:schemaLocation="http://www.example.com/gems gems.xsd">
    <gem origin="test" value="10" >
        <name>test</name>
        <preciousness>test</preciousness>
        <parameters>
            <color>test</color>
            <transparence>10</transparence>
            <facets>10</facets>
        </parameters>
    </gem>
</gems>
